/* Generated By:JavaCC: Do not edit this line. JTBParserConstants.java */
package EDU.purdue.jtb.parser;

public interface JTBParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int ABSTRACT = 9;
  int BOOLEAN = 10;
  int BREAK = 11;
  int BYTE = 12;
  int CASE = 13;
  int CATCH = 14;
  int CHAR = 15;
  int CLASS = 16;
  int CONST = 17;
  int CONTINUE = 18;
  int _DEFAULT = 19;
  int DO = 20;
  int DOUBLE = 21;
  int ELSE = 22;
  int EXTENDS = 23;
  int FALSE = 24;
  int FINAL = 25;
  int FINALLY = 26;
  int FLOAT = 27;
  int FOR = 28;
  int GOTO = 29;
  int IF = 30;
  int IMPLEMENTS = 31;
  int IMPORT = 32;
  int INSTANCEOF = 33;
  int INT = 34;
  int INTERFACE = 35;
  int LONG = 36;
  int NATIVE = 37;
  int NEW = 38;
  int NULL = 39;
  int PACKAGE = 40;
  int PRIVATE = 41;
  int PROTECTED = 42;
  int PUBLIC = 43;
  int RETURN = 44;
  int SHORT = 45;
  int STATIC = 46;
  int SUPER = 47;
  int SWITCH = 48;
  int SYNCHRONIZED = 49;
  int THIS = 50;
  int THROW = 51;
  int THROWS = 52;
  int TRANSIENT = 53;
  int TRUE = 54;
  int TRY = 55;
  int VOID = 56;
  int VOLATILE = 57;
  int WHILE = 58;
  int INTEGER_LITERAL = 59;
  int DECIMAL_LITERAL = 60;
  int HEX_LITERAL = 61;
  int OCTAL_LITERAL = 62;
  int FLOATING_POINT_LITERAL = 63;
  int EXPONENT = 64;
  int CHARACTER_LITERAL = 65;
  int STRING_LITERAL = 66;
  int LETTER = 67;
  int DIGIT = 68;
  int LPAREN = 69;
  int RPAREN = 70;
  int LBRACE = 71;
  int RBRACE = 72;
  int LBRACKET = 73;
  int RBRACKET = 74;
  int SEMICOLON = 75;
  int COMMA = 76;
  int DOT = 77;
  int ASSIGN = 78;
  int GT = 79;
  int LT = 80;
  int BANG = 81;
  int TILDE = 82;
  int HOOK = 83;
  int COLON = 84;
  int EQ = 85;
  int LE = 86;
  int GE = 87;
  int NE = 88;
  int SC_OR = 89;
  int SC_AND = 90;
  int INCR = 91;
  int DECR = 92;
  int PLUS = 93;
  int MINUS = 94;
  int STAR = 95;
  int SLASH = 96;
  int BIT_AND = 97;
  int BIT_OR = 98;
  int XOR = 99;
  int REM = 100;
  int LSHIFT = 101;
  int RSIGNEDSHIFT = 102;
  int RUNSIGNEDSHIFT = 103;
  int PLUSASSIGN = 104;
  int MINUSASSIGN = 105;
  int STARASSIGN = 106;
  int SLASHASSIGN = 107;
  int ANDASSIGN = 108;
  int ORASSIGN = 109;
  int XORASSIGN = 110;
  int REMASSIGN = 111;
  int LSHIFTASSIGN = 112;
  int RSIGNEDSHIFTASSIGN = 113;
  int RUNSIGNEDSHIFTASSIGN = 114;
  int EOF_TK = 115;
  int IGNORE_CASE_TK = 116;
  int JAVACODE_TK = 117;
  int LOOKAHEAD_TK = 118;
  int MORE_TK = 119;
  int OPTIONS_TK = 120;
  int PARSER_BEGIN_TK = 121;
  int PARSER_END_TK = 122;
  int SKIP_TK = 123;
  int SPECIAL_TOKEN_TK = 124;
  int TOKEN_TK = 125;
  int TOKEN_MGR_DECLS_TK = 126;
  int IDENTIFIER = 127;
  int POUND = 128;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"EOF\"",
    "\"IGNORE_CASE\"",
    "\"JAVACODE\"",
    "\"LOOKAHEAD\"",
    "\"MORE\"",
    "\"options\"",
    "\"PARSER_BEGIN\"",
    "\"PARSER_END\"",
    "\"SKIP\"",
    "\"SPECIAL_TOKEN\"",
    "\"TOKEN\"",
    "\"TOKEN_MGR_DECLS\"",
    "<IDENTIFIER>",
    "\"#\"",
  };

}
