//
// Generated by JTB 1.3.1
//

package EDU.purdue.jtb.syntaxtree;

/**
 * Grammar production:
 * f0 -> JavaCCOptions()
 * f1 -> <PARSER_BEGIN_TK>
 * f2 -> <LPAREN>
 * f3 -> <IDENTIFIER>
 * f4 -> <RPAREN>
 * f5 -> CompilationUnit()
 * f6 -> <PARSER_END_TK>
 * f7 -> <LPAREN>
 * f8 -> <IDENTIFIER>
 * f9 -> <RPAREN>
 * f10 -> ( Production() )*
 * f11 -> <EOF>
 */
public class JavaCCInput implements Node {
   public JavaCCOptions f0;
   public NodeToken f1;
   public NodeToken f2;
   public NodeToken f3;
   public NodeToken f4;
   public CompilationUnit f5;
   public NodeToken f6;
   public NodeToken f7;
   public NodeToken f8;
   public NodeToken f9;
   public NodeListOptional f10;
   public NodeToken f11;

   public JavaCCInput(JavaCCOptions n0, NodeToken n1, NodeToken n2, NodeToken n3, NodeToken n4, CompilationUnit n5, NodeToken n6, NodeToken n7, NodeToken n8, NodeToken n9, NodeListOptional n10, NodeToken n11) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
      f8 = n8;
      f9 = n9;
      f10 = n10;
      f11 = n11;
   }

   public JavaCCInput(JavaCCOptions n0, NodeToken n1, CompilationUnit n2, NodeToken n3, NodeListOptional n4) {
      f0 = n0;
      f1 = new NodeToken("PARSER_BEGIN");
      f2 = new NodeToken("(");
      f3 = n1;
      f4 = new NodeToken(")");
      f5 = n2;
      f6 = new NodeToken("PARSER_END");
      f7 = new NodeToken("(");
      f8 = n3;
      f9 = new NodeToken(")");
      f10 = n4;
      f11 = new NodeToken("");
   }

   public void accept(EDU.purdue.jtb.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(EDU.purdue.jtb.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(EDU.purdue.jtb.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(EDU.purdue.jtb.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

