//
// Generated by JTB 1.3.1
//

package EDU.purdue.jtb.syntaxtree;

/**
 * Grammar production:
 * f0 -> <LOOKAHEAD_TK>
 * f1 -> <LPAREN>
 * f2 -> [ <INTEGER_LITERAL> ]
 * f3 -> [ <COMMA> ]
 * f4 -> ExpansionChoices()
 * f5 -> [ <COMMA> ]
 * f6 -> [ <LBRACE> Expression() <RBRACE> ]
 * f7 -> <RPAREN>
 */
public class LocalLookahead implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NodeOptional f2;
   public NodeOptional f3;
   public ExpansionChoices f4;
   public NodeOptional f5;
   public NodeOptional f6;
   public NodeToken f7;

   public LocalLookahead(NodeToken n0, NodeToken n1, NodeOptional n2, NodeOptional n3, ExpansionChoices n4, NodeOptional n5, NodeOptional n6, NodeToken n7) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
   }

   public LocalLookahead(NodeOptional n0, NodeOptional n1, ExpansionChoices n2, NodeOptional n3, NodeOptional n4) {
      f0 = new NodeToken("LOOKAHEAD");
      f1 = new NodeToken("(");
      f2 = n0;
      f3 = n1;
      f4 = n2;
      f5 = n3;
      f6 = n4;
      f7 = new NodeToken(")");
   }

   public void accept(EDU.purdue.jtb.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(EDU.purdue.jtb.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(EDU.purdue.jtb.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(EDU.purdue.jtb.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

