//
// Generated by JTB 1.3.1
//

package EDU.purdue.jtb.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(EDU.purdue.jtb.visitor.Visitor v);
   public <R,A> R accept(EDU.purdue.jtb.visitor.GJVisitor<R,A> v, A argu);
   public <R> R accept(EDU.purdue.jtb.visitor.GJNoArguVisitor<R> v);
   public <A> void accept(EDU.purdue.jtb.visitor.GJVoidVisitor<A> v, A argu);
   public void accept(EDU.purdue.jtb.visitor.ThreadedVisitor v);
}

