//
// Generated by JTB 1.3.1
//

package EDU.purdue.jtb.syntaxtree;

/**
 * Grammar production:
 * f0 -> <TOKEN_MGR_DECLS_TK>
 * f1 -> <COLON>
 * f2 -> ClassBody()
 */
public class TokenManagerDecls implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public ClassBody f2;

   public TokenManagerDecls(NodeToken n0, NodeToken n1, ClassBody n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public TokenManagerDecls(ClassBody n0) {
      f0 = new NodeToken("TOKEN_MGR_DECLS");
      f1 = new NodeToken(":");
      f2 = n0;
   }

   public void accept(EDU.purdue.jtb.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(EDU.purdue.jtb.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(EDU.purdue.jtb.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(EDU.purdue.jtb.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

